[pytest]
testpaths = tests
markers =
    application: Application tests
    point: Point tests
    material: Material tests
    frame: Frame tests
    cable: Cable tests
    area: Area tests
    link: Link tests
    loading: Loading tests
